@startuml

digraph Q {

  rankdir=LR
  node [style=rounded, shape=box, width=1.2, height=1, style=filled, fontname="Courier"]


  subgraph cluster_dings01 {
    fontname="Courier"
    label="dings01"
    bgcolor=bisque
    fontsize="20"

    dings_receive [bgcolor=yellow label="Receive\nport"];
    dings_send [bgcolor=yellow label="Send\nport"];
  }

  subgraph cluster_computer {
    fontname="Courier"
    label="Ableton Live"
    bgcolor=lavender
    fontsize="20"

    m4l_receive [bgcolor=yellow label="Receive\nport"];
    m4l_send [bgcolor=yellow label="Send\nport"];
  }

  dings_send -> m4l_receive [label="e.g. 10000" fontname=Courier]
  m4l_send -> dings_receive [label="e.g. 12000" fontname=Courier]

}

@enduml